import type { NextPage } from "next";
import Head from "next/head";
import React from "react";

import OverlayScreen from "../components/OverlayScreen";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>PomodoroTunes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen w-full flex-col items-center justify-center overflow-hidden">
        <video
          autoPlay
          loop
          muted
          className="absolute top-0 left-0 z-0 h-[100vh] w-[100vw] object-cover "
        >
          <source
            src="pixelart/test5.mp4"
            type="video/mp4"
            className="w-[100%]"
          />
        </video>
        <OverlayScreen />
      </main>
    </>
  );
};

export default Home;
